FROM apache/airflow:2.8.1-python3.11

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

USER airflow
# Only install the essentials for Airflow and Postgres connectivity
# We don't install xgboost/scikit-learn here to keep the image small and fast.
RUN pip install --no-cache-dir \
    "apache-airflow-providers-http" \
    "psycopg[binary]"
