apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    version: 1
    editable: true
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
      search:
        hide: false
      lokiSearch:
        datasourceUid: loki
      tracesToLogs:
        datasourceUid: loki
        filterByTraceId: true
        filterBySpanId: false
        mapTagNamesEnabled: false
      tracesToMetrics:
        datasourceUid: prometheus
        spanTimer:
          operationParams:
            - key: http.method
              value: GET
          operationName: http.server.duration
